repo: dongitran/Good-Job
environment: null
type: secret

secrets:
  # Pulumi Cloud access token for state management
  # Bitwarden: Pulumi/
  - name: PULUMI_ACCESS_TOKEN
    bitwarden: PULUMI_ACCESS_TOKEN_GCP_INFRA
